modLoader="javafml"
loaderVersion="[36,)"
license="MIT"
issueTrackerURL=""

[[mods]]
modId="shinytoken"
version="0.0.0"
displayName="Shiny Token"
displayURL=""
credits=""
authors=""
description=""

[[dependencies.shinytoken]]
modId="forge"
mandatory=true
versionRange="[47.1.28,)"
ordering="NONE"
side="BOTH"

[[dependencies.shinytoken]]
modId="minecraft"
mandatory=true
versionRange="[1.20.1,1.21)"
ordering="NONE"
side="BOTH"