modLoader="javafml"
loaderVersion="[36,)"
license="MIT"
issueTrackerURL="https://github.com/alex-ajsdev/PixelTokens/issues"

[[mods]]
modId="pixeltokens"
version="0.1.0"
displayName="Pixel Tokens"
displayURL="https://github.com/alex-ajsdev"
credits="https://github.com/alex-ajsdev"
authors="https://github.com/alex-ajsdev"
description="Adds PixelTokens"

[[dependencies.pixeltokens]]
modId="forge"
mandatory=true
versionRange="[47.1.28,)"
ordering="NONE"
side="BOTH"

[[dependencies.pixeltokens]]
modId="minecraft"
mandatory=true
versionRange="[1.20.1,1.21)"
ordering="NONE"
side="BOTH"