modLoader="javafml"
loaderVersion="[36,)"
license=""
issueTrackerURL=""

[[mods]]
modId="examplemod"
version="0.0.0"
displayName="Example Mod"
displayURL=""
credits=""
authors=""
description=""

[[dependencies.examplemod]]
modId="forge"
mandatory=true
versionRange="[47.1.28,)"
ordering="NONE"
side="BOTH"

[[dependencies.examplemod]]
modId="minecraft"
mandatory=true
versionRange="[1.20.1,1.21)"
ordering="NONE"
side="BOTH"