modLoader="javafml"
loaderVersion="[36,)"
license="MIT"
issueTrackerURL="https://github.com/alex-ajsdev/ShinyToken/issues"

[[mods]]
modId="shinytoken"
version="0.1.0"
displayName="Shiny Token"
displayURL="https://github.com/alex-ajsdev"
credits="https://github.com/alex-ajsdev"
authors="https://github.com/alex-ajsdev"
description="Adds ShinyToken"

[[dependencies.shinytoken]]
modId="forge"
mandatory=true
versionRange="[47.1.28,)"
ordering="NONE"
side="BOTH"

[[dependencies.shinytoken]]
modId="minecraft"
mandatory=true
versionRange="[1.20.1,1.21)"
ordering="NONE"
side="BOTH"